### ISSUE TITLE
UnhandledPromiseRejectionWarning: Unhandled promise rejection

### ISSUE THREAD

**Issue by bennyn** [wireapp/proteus.js#19]
Node v6 throws warnings when Promise rejections are not handled ([The 10 Key Features in Node.js v6 LTS Boron After You Upgrade](https://nodesource.com/blog/the-10-key-features-in-node-js-v6-lts-boron-after-you-upgrade/)).

Our [SessionSpec](https://github.com/wireapp/proteus.js/blob/master/test/session/SessionSpec.coffee#L154) surfaces unhandled rejections. 

**For example:** `bob.decrypt bob_store, hello_bob_delayed` causes an `UnhandledPromiseRejectionWarning`. We need to get rid of these warnings as these errors terminate the Node process with a non-zero exit code.

Error is:
> TypeError: Cannot read property 'key_pair' of undefined

**Comment by herrmannplatz** [comment]
You can reuse the existing Promise

```coffeescript
 _new_state: (prekey_store, prekey_message) ->
  return prekey_store.get_prekey prekey_message.prekey_id
  .then (prekey) =>
    if prekey
      return SessionState.init_as_bob @local_identity, prekey.key_pair, prekey_message.identity_key, prekey_message.base_key
    throw new Error('Unable to get PreKey')
```

**Comment by bennyn** [comment]
Done with https://github.com/wireapp/proteus.js/releases/tag/v2.1.3
