### ISSUE TITLE
Session._evict_oldest_session_state() fails as oldest is undefined (Error code 8391)

### ISSUE THREAD

**Issue by gregor** [wireapp/proteus.js#3]
There error reports where the eviction of the latest session state raises and error (hased to code 8391) as the state reduction returns null causing the decryption of a message to fail.

https://github.com/wireapp/proteus.js/blob/c07092b66b84e107558e0ad3985ef1b7337686bd/src/proteus/session/Session.coffee#L166

**Comment by ffflorian** [comment]
Fixed in https://github.com/wireapp/proteus.js/commit/620c8a6df74caa19386e6ed64f7368e6ee3a7749.
