### ISSUE TITLE
Replace libsodium.js fork with standard libsodium.js

### ISSUE THREAD

**Issue by bennyn** [wireapp/proteus.js#32]
At the moment we use a libsodium fork: https://github.com/wireapp/libsodium.js

In the future we want to use the official libsodium Sumo version:

```javascript
var sodium = require('libsodium-wrappers-sumo');
```

The only problem we face is that `sodium.crypto_stream_chacha20_xor` is not exposed (jedisct1/libsodium.js#73). So we need to find a replacement for this specific function.

There are alternative ChaCha20 implementations (also with `XORKeyStream`) like:
- https://github.com/aead/chacha20
- http://insanecoding.blogspot.de/2014/06/avoid-incorrect-chacha20-implementations.html

Our  special case is, that we don't use Authenticated Encryption with Associated Data (AEAD) directly. Instead we are using a combination of ChaCha20 (the stream cipher) and HMAC-SHA256 as MAC, in an [Encrypt-then-MAC](https://en.wikipedia.org/wiki/Authenticated_encryption#Encrypt-then-MAC_.28EtM.29) (EtM) process. That's why we need to be really careful when replacing `sodium.crypto_stream_chacha20_xor`. 

Our best bet at the moment would be an exact copy of `sodium.crypto_stream_chacha20_xor` inside a seperate repository, so that we can do something like:

```javascript
var sodium = require('libsodium-wrappers-sumo');
var crypto_stream_chacha20_xor = require('crypto_stream_chacha20_xor');
```

**Comment by ffflorian** [comment]
Fixed in https://github.com/wireapp/proteus.js/commit/9a557d7013066b27768f4d1e612dbf816fec332f.
