### ISSUE TITLE
Use "libsodium-neon"

### ISSUE THREAD

**Issue by bennyn** [wireapp/proteus.js#41]
Proteus should check the `global` object for `global.sodiumneon`. If found, it should take `sodiumneon`'s functions in favor of the `libsodium-wrappers-sumo`'s functions.

**Comment by bennyn** [comment]
We could also use an optional dependency like we did with the `node-addressbook`:

```json
"optionalDependencies": {
  "node-addressbook": "https://github.com/wireapp/node-addressbook.git#2.0.0"
}
```

Then we do a `try-catch` to require the dependency (if it could be built). As a last step `Object.assign` can concatenate the `libsodium.js` & `libsodium-neon`.

**Comment by ffflorian** [comment]
Fixed in https://github.com/wireapp/proteus.js/commit/4c0103d8bb04cf6ebd2c8b23ceaecbaf9fd332c2.
