### ISSUE TITLE
Automatically generate definition file (proteus.d.ts)

### ISSUE THREAD

**Issue by bennyn** [wireapp/proteus.js#42]
At the moment our type definitions are handwritten:
- https://github.com/wireapp/proteus.js/blob/master/dist/typings/proteus.d.ts

It would be nice if we could generate types automatically from JSDoc comments. 

The [protobuf.js](https://github.com/dcodeIO/protobuf.js) uses [tsd-jsdoc](https://github.com/englercj/tsd-jsdoc) to do this.

**Comment by bennyn** [comment]
Blocked by: https://github.com/englercj/tsd-jsdoc/issues/16

**Comment by ffflorian** [comment]
Fixed in https://github.com/wireapp/proteus.js/commit/5b8670f898ec0a9f330442ad05b0c9530bda3395.
